url: https://estrogen.rocks
google_analytics: UA-168919706-1
email: estrogenrocks@protonmail.com
theme: jekyll-theme-midnight
show_downloads: false
safe: true #to make sure github stuff works
markdown: CommonMarkGhPages # used to make code blocks inside of details+summary
plugins:
  - jekyll-seo-tag #works with github pages

# seo
logo: /assets/transflag.png
title: Estrogen.rocks
tagline: MtF Resource Aggregate
description: MtF Resource Aggregate