title: Estrogen.rocks
url: https://estrogen.rocks
google_analytics: UA-168919706-1
webmaster_verifications:
  google: aSDLTEh-A5tX85V-eILSvBE3z9CK3b9MWGWp-ePxP5E
tagline: MtF Resource Aggregate
description: MtF Resource Aggregate
email: estrogenrocks@protonmail.com
theme: jekyll-theme-midnight
show_downloads: false
safe: true #to make sure github stuff works
markdown: CommonMarkGhPages # used to make code blocks inside of details+summary
plugins:
  - jekyll-seo-tag #works with github pages